= COCONUT - Bluebook
:navtitle: Home
:description: Welcome to COCONUT - Bluebook, the foundation for all COCONUT activities
:keywords: COCONUT, Bluebook, INESA, digital transformation, rural development

== Introduction
Welcome to the *COCONUT Bluebook*, the foundational guide for all activities organized by COCONUT in each period. This Bluebook serves as a comprehensive resource outlining our initiatives, processes, and goals to empower communities through technology and innovation, with a focus on rural digital transformation.

COCONUT, established as a think tank in April 2008, drives impactful programs such as internal and external initiatives such as Now Open, ROOT (Research Orientation Of Training), Learning, INESA (Inovasi & Edukasi Desa), On Boarding & Meeting, each of which has had a huge impact from various parties both internally and externally. Explore the sections below to learn more about our structured approach to community engagement and innovation.

== Explore the Bluebook
- xref:module-one/now-open.adoc[Now Open]
- xref:module-one/root.adoc[ROOT]
- xref:module-one/learning.adoc[Learning]
- xref:module-one/coconut-draft-inesa.adoc[INESA]
- xref:module-one/onboarding.adoc[Onboarding]
- xref:module-one/meeting.adoc[Meeting]

Dive into these sections to understand how COCONUT organizes its activities, from recruitment and onboarding to learning programs and strategic meetings, all aimed at creating a lasting impact.
