name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Bersihkan cache dan build
      - name: Clean cache and build
        run: |
          rm -rf .cache build

      # Build dengan Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache --stacktrace /home/inesa/BlueBook/antora-playbook.yml

      # Deploy ke VPS melalui SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo rm -rf /var/www/html/build
            sudo scp -r /home/inesa/BlueBook/build /var/www/html/
            sudo chown $USER:$USER /var/www/html/build

      # Unggah artefak build
      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "build"
          target: "/var/www/html/"

      # Finalisasi deployment
      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/build
            sudo chmod -R 755 /var/www/html/build
            sudo nginx -t
            sudo systemctl restart nginx
